### ISSUE TITLE
Update assignment bookmarklet

### ISSUE THREAD

**Issue by plocket** [michaelaltmann/get-your-refund#12]
(Should some of these be broken out into their own issue?)

> - It should have 1-click assign-to and unassign. We think it may have broken with one of the eng changes
> - Current Problem: the bookmarklet makes the greeter name appear 2x in the assignment dropdown
> - Suggested updates:
>    - Remove the double listing of greeter name in the dropdown
>    - I believe the alphabetical component will also be excess code now
>    - Consider whether we want to invest effort into fixing the 1-click functionality
>       - Katie has noticed this is helpful to have, e.g. to assign 10 clients to yourself directly from the All Clients view
> - Bug found by Katie: If you have it filtered as assigned to a user, and you want to un-filter for an assigned user, you can select “ “ at the top of the dropdown and Filter, but the assigned user remains filtered
>    - Workaround: Use the “Clear” to remove all filters
> - Flag Clients to not work on bookmarklet feedback
> - Mary noticed a few that were not flagged appropriately

[See doc](https://docs.google.com/document/d/1FQYTF4KIEpmEUO_0wgbxsWQdsoqUnstOl5n4BGWhA34/edit?pli=1#bookmark=id.fub3ihpeu76m).

**Comment by michaelaltmann** [comment]
I think the major issue is that CfA changed from a span tag to a div tag.  I will create a PR.

**Comment by michaelaltmann** [comment]
CfA changed to DOM to use a div rather than a span
